### ISSUE TITLE
Tests seem to be failing

### ISSUE THREAD

**Issue by iDev0urer** [Metrime/gulp-batch-replace#3]
I just forked this, ran `npm install`, and ran `npm test` and I got the following results:

```shell
> gulp-batch-replace@0.0.0 test /home/chris/projects/forks/gulp-batch-replace
> mocha

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  ․․․․․․

  3 passing (23ms)
  3 failing

  1) gulp-batch-replace replacePlugin() should replace string with string on a stream:
     Uncaught AssertionError: expected <Buffer 48 65 6c 6c 6f 20 77 65 69 72 64 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 66 75 6e 6b 79 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 6c 6f 76 65 ... > to equal 'Hello weird person!\nHello funky person!\nHello lovely person!\nHello amazing person!\n'
      at Object.Assertion.equal (/home/chris/projects/forks/gulp-batch-replace/node_modules/should/lib/should.js:389:10)
      at /home/chris/projects/forks/gulp-batch-replace/test/main.js:59:23
      at Stream.<anonymous> (/home/chris/projects/forks/gulp-batch-replace/node_modules/event-stream/index.js:306:20)
      at _end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:74:5)
      at Stream.onend (stream.js:59:10)
      at emitNone (events.js:85:20)
      at Stream.emit (events.js:179:7)
      at end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:116:39)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:122:5)
      at ReadStream.onend (_stream_readable.js:498:10)
      at ReadStream.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at ReadStream.emit (events.js:179:7)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) gulp-batch-replace replacePlugin() should replace regex with string on a stream:
     Uncaught AssertionError: expected <Buffer 48 65 6c 6c 6f 20 77 65 69 72 64 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 66 75 6e 6b 79 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 6c 6f 76 65 ... > to equal 'Hello weird person!\nHello funky person!\nHello lovely person!\nHello amazing person!\n'
      at Object.Assertion.equal (/home/chris/projects/forks/gulp-batch-replace/node_modules/should/lib/should.js:389:10)
      at /home/chris/projects/forks/gulp-batch-replace/test/main.js:83:23
      at Stream.<anonymous> (/home/chris/projects/forks/gulp-batch-replace/node_modules/event-stream/index.js:306:20)
      at _end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:74:5)
      at Stream.onend (stream.js:59:10)
      at emitNone (events.js:85:20)
      at Stream.emit (events.js:179:7)
      at end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:116:39)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:122:5)
      at ReadStream.onend (_stream_readable.js:498:10)
      at ReadStream.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at ReadStream.emit (events.js:179:7)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  3) gulp-batch-replace replacePlugin() should replace mixed search types on a stream:
     Uncaught AssertionError: expected <Buffer 48 65 6c 6c 6f 20 77 65 69 72 64 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 66 75 6e 6b 79 20 70 65 72 73 6f 6e 21 0a 48 65 6c 6c 6f 20 6c 6f 76 65 ... > to equal 'Hello weird person!\nHello funky person!\nHello lovely person!\nHello amazing person!\n'
      at Object.Assertion.equal (/home/chris/projects/forks/gulp-batch-replace/node_modules/should/lib/should.js:389:10)
      at /home/chris/projects/forks/gulp-batch-replace/test/main.js:170:23
      at Stream.<anonymous> (/home/chris/projects/forks/gulp-batch-replace/node_modules/event-stream/index.js:306:20)
      at _end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/through/index.js:74:5)
      at Stream.onend (stream.js:59:10)
      at emitNone (events.js:85:20)
      at Stream.emit (events.js:179:7)
      at end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:116:39)
      at Stream.stream.end (/home/chris/projects/forks/gulp-batch-replace/node_modules/map-stream/index.js:122:5)
      at ReadStream.onend (_stream_readable.js:498:10)
      at ReadStream.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at ReadStream.emit (events.js:179:7)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)



npm ERR! Test failed.  See above for more details.
```

Node version: v5.11.1
Npm version: 3.8.6
Gulp version: 3.9.1

I'm looking into it now

**Comment by iDev0urer** [comment]
Fixed with #4 :bow:
